### ISSUE TITLE
Fails to build with Python 3.12

### ISSUE THREAD

**Issue by glaubitz** [Azure/azure-uamqp-python#379]
Building uamqp 1.6.8 with Python 3.12 fails with the following error message:

```
[   84s] uamqp/c_uamqp.c: In function ‘__Pyx_PyInt_As_unsigned_char’:
[   84s] uamqp/c_uamqp.c:111279:53: error: ‘PyLongObject’ {aka ‘struct _longobject’} has no member named ‘ob_digit’
[   84s] 111279 |             const digit* digits = ((PyLongObject*)x)->ob_digit;
[   84s]        |
```

Full build log available in: https://build.opensuse.org/package/live_build_log/devel:languages:python:azure/python-uamqp/openSUSE_Tumbleweed/x86_64
